language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

env:
  - TEST_CONFIG="app/phpunit.xml.dist"

script: ./bin/security-checker security:check
script: phpunit -c $TEST_CONFIG --colors --coverage-text
script: ./bin/phpmd src/ text codesize,naming

notifications:
    on_success: never
    on_failure: always
