language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

env:
  - TEST_CONFIG="app/phpunit.xml.dist"

addons:
  apt:
    packages:
      - sshpass

script:
  - ./bin/security-checker security:check
  - phpunit -c $TEST_CONFIG --colors --coverage-text
  - ./bin/phpmd src/ text codesize,naming

after_success:
  - export SYMFONY_ENV=prod && composer install --no-dev -o
  - mkdir build
  - mv * build
  - tar -czf build.tgz build
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USERNAME@$DEPLOY_SERVER:/$DEPLOY_PATH

notifications:
  on_success: never
  on_failure: always