language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -c app/phpunit.xml.dist

notifications:
    on_success: never
    on_failure: always
