language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

env:
  - TEST_CONFIG="app/phpunit.xml.dist"

addons:
  apt:
    packages:
      - sshpass

script:
  - ./bin/security-checker security:check
  - phpunit -c $TEST_CONFIG --colors --coverage-text
  - ./bin/phpmd src/ text codesize,naming

after_success:
  - export SYMFONY_ENV=prod && composer install --no-dev -o
  - mkdir build
  - find . -maxdepth 1 | grep -vE "build|.|.."| xargs -i mv {} ./build
  - tar -czf build.tgz build
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e scp -o stricthostkeychecking=no ssh $DEPLOY_USER@$DEPLOY_HOST tar -xzf $DEPLOY_PATH/build.tgz -C $DEPLOY_PROD_PATH

notifications:
  on_success: never
  on_failure: always