---
configs:
  box: 'debian/jessie64'
  public_ip: '192.168.2.2'
  hostname: '010php.vm'
  displayname: '010php.vm'
  vagrant_required_version: '1.5'
  vagrant_memory_size: '256'
  vagrant_ssh_forward_agent: 'true'
  vagrant_synced_folder: '/vagrant'

