services:

  website.meetup_client:
      class: DMS\Service\Meetup\MeetupKeyAuthClient
      factory: [DMS\Service\Meetup\MeetupKeyAuthClient, factory]
      arguments: ['%meetup%']

  website.services.meetup:
      class: WebsiteBundle\Services\Meetup
      arguments: ['@website.meetup_client', '@stash', '%meetup%']
